In [9]:
import numpy as np
import scipy.stats as scs
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [1]:
from read_file import read_input

In [42]:
tracks = read_input('input_13.txt', '\n')[:-1]

In [6]:
tracks[0]

'                                             /---------------------------------------------------------------------------------------------\\          '

In [45]:
listed = [[letter for letter in track] for track in tracks]

In [47]:
np_tracks = np.array(listed)

In [70]:
np.where(np.isin(np_tracks, ['<', '>', '^', 'v']))

(array([  1,   9,  19,  22,  22,  37,  39,  46,  58,  83,  91, 103, 116,
        123, 135, 139, 145]),
 array([ 24,  82, 122,  31,  61,  25,  28,  81, 134,  90, 147,  29,  76,
         99,  79,  91,   3]))

In [71]:
np_tracks[1, 24]

'<'

In [231]:
fa = np.array(np.where(np.isin(np_tracks, ['<', '>', '^', 'v']))).T

In [76]:
carts = _

In [99]:
cart_moves = {'west': np.array([0, -1]),
              'east': np.array([0, 1]),
              'north': np.array([-1, 0]),
              'south': np.array([1, 0])}
cart_orientations = {'<': 'west',
                     '>': 'east',
                     '^': 'north',
                     'v': 'south'}
cardinal_dirs = {'north': {'left': 'west', 'straight': 'north', 'right': 'east'},
                 'south': {'left': 'east', 'straight': 'south', 'right': 'west'},
                 'west': {'left': 'south', 'straight': 'west', 'right': 'north'},
                 'east': {'left': 'north', 'straight': 'east', 'right': 'south'}
}

In [114]:
current_orientations = np.array([cart_orientations[np_tracks[row, col]] for row, col in carts])

In [115]:
current_orientations

array(['west', 'west', 'north', 'east', 'east', 'east', 'south', 'west',
       'south', 'east', 'north', 'north', 'east', 'west', 'east', 'east',
       'west'], dtype='<U5')

In [116]:
next_moves = np.array(['left' for _ in range(len(current_orientations))], dtype='<U8')

In [117]:
def change_direction(cart_row_num, next_moves, current_orientations):
    next_move = next_moves[cart_row_num]
    curr_dir = current_orientations[cart_row_num]
    current_orientations[cart_row_num] = cardinal_dirs[curr_dir][next_move]
    if next_move == 'left':
        next_next_move = 'straight'
    elif next_move == 'straight':
        next_next_move = 'right'
    else:
        next_next_move = 'left'
    next_moves[cart_row_num] = next_next_move

In [125]:
change_direction(1, next_moves, current_orientations)

In [126]:
current_orientations

array(['west', 'west', 'north', 'east', 'east', 'east', 'south', 'west',
       'south', 'east', 'north', 'north', 'east', 'west', 'east', 'east',
       'west'], dtype='<U5')

In [127]:
next_moves

array(['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left',
       'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left',
       'left'], dtype='<U8')

In [387]:
def find_crash():
    tracks = read_input('input_13.txt', '\n')[:-1]
    listed = [[letter for letter in track] for track in tracks]
    np_tracks = np.array(listed)
#     new_ex = """/->-\        
# |   |  /----\\
# | /-+--+-\  |
# | | |  | v  |
# \-+-/  \-+--/
#   \------/   """
#     split_t = new_ex.split('\n')
#     np_tracks = np.array([list(t) for t in split_t])
    carts = np.array(np.where(np.isin(np_tracks, ['<', '>', '^', 'v']))).T
    cart_moves = {'west': np.array([0, -1]),
                  'east': np.array([0, 1]),
                  'north': np.array([-1, 0]),
                  'south': np.array([1, 0])}
    cart_orientations = {'<': 'west',
                         '>': 'east',
                         '^': 'north',
                         'v': 'south'}
    cardinal_dirs = {'north': {'left': 'west', 'straight': 'north', 'right': 'east'},
                     'south': {'left': 'east', 'straight': 'south', 'right': 'west'},
                     'west': {'left': 'south', 'straight': 'west', 'right': 'north'},
                     'east': {'left': 'north', 'straight': 'east', 'right': 'south'}}
    current_orientations = np.array([cart_orientations[np_tracks[row, col]] for row, col in carts])
    next_moves = np.array(['left' for _ in range(len(current_orientations))], dtype='<U8')
    while True:
        #import pdb; pdb.set_trace()
        lexsorted = np.lexsort((carts[:, 1], carts[:, 0]))
        carts = carts[lexsorted]
        next_moves = next_moves[lexsorted]
        current_orientations = current_orientations[lexsorted]
        for i, cart in enumerate(carts):
#             if np.all(carts[i] == np.array([17, 36])):
#                 import pdb; pdb.set_trace()
            carts[i] += cart_moves[current_orientations[i]]
            #these_spots = [np_tracks[row, col] for row, col in carts]
            spot = np_tracks[carts[i][0], carts[i][1]]
            if len(carts) != len(np.unique(carts, axis=0)):
                return carts
            if spot == '+':
                change_direction(i, next_moves, current_orientations)
            elif spot == '\\':
                if current_orientations[i] == 'west':
                    new_orientation = 'north'
                elif current_orientations[i] == 'east':
                    new_orientation = 'south'
                elif current_orientations[i] == 'north':
                    new_orientation = 'west'
                elif current_orientations[i] == 'south':
                    new_orientation = 'east'
                current_orientations[i] = new_orientation
            elif spot == '/':
                if current_orientations[i] == 'west':
                    new_orientation = 'south'
                elif current_orientations[i] == 'east':
                    new_orientation = 'north'
                elif current_orientations[i] == 'north':
                    new_orientation = 'east'
                elif current_orientations[i] == 'south':
                    new_orientation = 'west'
                current_orientations[i] = new_orientation
            elif spot in '-|<>^v':
                continue
            else:
                import pdb; pdb.set_trace()
                return "You screwed up in spots"
    return carts

In [386]:
find_crash()

array([[  6, 107],
       [ 16,  99],
       [ 25,   4],
       [ 32,  69],
       [ 43, 143],
       [ 43, 143],
       [ 49,  83],
       [ 55, 148],
       [ 59,  43],
       [ 64,  99],
       [ 83, 107],
       [103,  60],
       [109,  98],
       [118,  37],
       [125, 104],
       [128,  13],
       [130,  41]])

In [316]:
np_tracks[18, 36]

'+'

In [158]:
tem = [(row, col) for row, col in carts]

In [166]:
np_tracks[38, 92]

'+'

In [221]:
c = np.array([[4, 4], [0, 1], [2, 3]])

In [222]:
c.sort(axis=0)

In [223]:
c

array([[0, 1],
       [2, 3],
       [4, 4]])

In [134]:
len(c) == len(np.unique(c, axis=0))

False

In [135]:
len(np.unique(c, axis=0))

2

In [136]:
np.array([cart_moves[pos] for pos in current_orientations])

array([[ 0, -1],
       [ 0, -1],
       [-1,  0],
       [ 0,  1],
       [ 0,  1],
       [ 0,  1],
       [ 1,  0],
       [ 0, -1],
       [ 1,  0],
       [ 0,  1],
       [-1,  0],
       [-1,  0],
       [ 0,  1],
       [ 0, -1],
       [ 0,  1],
       [ 0,  1],
       [ 0, -1]])

In [137]:
carts

array([[  1,  24],
       [  9,  82],
       [ 19, 122],
       [ 22,  31],
       [ 22,  61],
       [ 37,  25],
       [ 39,  28],
       [ 46,  81],
       [ 58, 134],
       [ 83,  90],
       [ 91, 147],
       [103,  29],
       [116,  76],
       [123,  99],
       [135,  79],
       [139,  91],
       [145,   3]])

In [139]:
np.unique(np_tracks)

array([' ', '+', '-', '/', '<', '>', '\\', '^', 'v', '|'], dtype='<U1')

In [207]:
new_ex = """/->-\        
|   |  /----\\
| /-+--+-\  |
| | |  | v  |
\-+-/  \-+--/
  \------/   """

In [208]:
new_ex

'/->-\\        \n|   |  /----\\\n| /-+--+-\\  |\n| | |  | v  |\n\\-+-/  \\-+--/\n  \\------/   '

In [209]:
split_t = new_ex.split('\n')

In [210]:
[len(x) for x in split_t]

[13, 13, 13, 13, 13, 13]

In [213]:
np.array([list(t) for t in split_t])

array([['/', '-', '>', '-', '\\', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['|', ' ', ' ', ' ', '|', ' ', ' ', '/', '-', '-', '-', '-', '\\'],
       ['|', ' ', '/', '-', '+', '-', '-', '+', '-', '\\', ' ', ' ', '|'],
       ['|', ' ', '|', ' ', '|', ' ', ' ', '|', ' ', 'v', ' ', ' ', '|'],
       ['\\', '-', '+', '-', '/', ' ', ' ', '\\', '-', '+', '-', '-',
        '/'],
       [' ', ' ', '\\', '-', '-', '-', '-', '-', '-', '/', ' ', ' ', ' ']],
      dtype='<U1')

In [226]:
carts == fa.sort(axis=0)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [227]:
fa

array([[  1,   3],
       [  9,  24],
       [ 19,  25],
       [ 22,  28],
       [ 22,  29],
       [ 37,  31],
       [ 39,  61],
       [ 46,  76],
       [ 58,  79],
       [ 83,  81],
       [ 91,  82],
       [103,  90],
       [116,  91],
       [123,  99],
       [135, 122],
       [139, 134],
       [145, 147]])

In [229]:
carts.argsort(axis=0)

array([[ 0, 16],
       [ 1,  0],
       [ 2,  5],
       [ 3,  6],
       [ 4, 11],
       [ 5,  3],
       [ 6,  4],
       [ 7, 12],
       [ 8, 14],
       [ 9,  7],
       [10,  1],
       [11,  9],
       [12, 15],
       [13, 13],
       [14,  2],
       [15,  8],
       [16, 10]])

In [230]:
carts

array([[  1,  24],
       [  9,  82],
       [ 19, 122],
       [ 22,  31],
       [ 22,  61],
       [ 37,  25],
       [ 39,  28],
       [ 46,  81],
       [ 58, 134],
       [ 83,  90],
       [ 91, 147],
       [103,  29],
       [116,  76],
       [123,  99],
       [135,  79],
       [139,  91],
       [145,   3]])

In [232]:
fa

array([[  1,  24],
       [  9,  82],
       [ 19, 122],
       [ 22,  31],
       [ 22,  61],
       [ 37,  25],
       [ 39,  28],
       [ 46,  81],
       [ 58, 134],
       [ 83,  90],
       [ 91, 147],
       [103,  29],
       [116,  76],
       [123,  99],
       [135,  79],
       [139,  91],
       [145,   3]])

In [235]:
next_moves[[1,2, 3]] = np.array(['right', 'right', 'right'])

In [237]:
next_moves[[2, 1, 0]]

array(['right', 'right', 'left'], dtype='<U8')

In [247]:
argsorted = carts.argsort(axis=0)
next_moves = next_moves[argsorted[:, 0]]

In [241]:
next_moves

array(['left', 'right', 'right', 'right', 'left', 'left', 'left', 'left',
       'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left',
       'left'], dtype='<U8')

In [253]:
np.random.shuffle(argsorted)

In [257]:
next_moves[argsorted[:, 0]]

array(['right', 'left', 'left', 'left', 'left', 'left', 'left', 'right',
       'right', 'left', 'left', 'left', 'left', 'left', 'left', 'left',
       'left'], dtype='<U8')

In [255]:
argsorted

array([[ 2,  5],
       [16, 10],
       [10,  1],
       [ 8, 14],
       [ 4, 11],
       [11,  9],
       [ 0, 16],
       [ 3,  6],
       [ 1,  0],
       [ 7, 12],
       [ 9,  7],
       [13, 13],
       [12, 15],
       [15,  8],
       [ 6,  4],
       [14,  2],
       [ 5,  3]])

In [263]:
carts

array([[  1,  24],
       [  9,  82],
       [ 19, 122],
       [ 22,  31],
       [ 22,  61],
       [ 37,  25],
       [ 39,  28],
       [ 46,  81],
       [ 58, 134],
       [ 83,  90],
       [ 91, 147],
       [103,  29],
       [116,  76],
       [123,  99],
       [135,  79],
       [139,  91],
       [145,   3]])

In [277]:
frind = carts.copy()

In [280]:
frind[frind[:, 0].argsort()] == carts

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [276]:
carts

array([[  1,  24],
       [  9,  82],
       [ 19, 122],
       [ 22,  31],
       [ 22,  61],
       [ 37,  25],
       [ 39,  28],
       [ 46,  81],
       [ 58, 134],
       [ 83,  90],
       [ 91, 147],
       [103,  29],
       [116,  76],
       [123,  99],
       [135,  79],
       [139,  91],
       [145,   3]])

In [274]:
frind

array([[  1,  24],
       [  9,  82],
       [ 19, 122],
       [ 22,  31],
       [ 22,  61],
       [ 25,  37],
       [ 28,  39],
       [ 46,  81],
       [ 58, 134],
       [ 83,  90],
       [ 91, 147],
       [ 29, 103],
       [ 76, 116],
       [ 99, 123],
       [ 79, 135],
       [ 91, 139],
       [  3, 145]])

In [267]:
frind

array([[  1,   3],
       [  9,  24],
       [ 19,  25],
       [ 22,  28],
       [ 22,  29],
       [ 37,  31],
       [ 39,  61],
       [ 46,  76],
       [ 58,  79],
       [ 83,  81],
       [ 91,  82],
       [103,  90],
       [116,  91],
       [123,  99],
       [135, 122],
       [139, 134],
       [145, 147]])

In [287]:
argsorted = carts[:, 0].argsort()



In [288]:
argsorted

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [289]:
carts = carts[argsorted]

In [290]:
carts

array([[  1,  24],
       [  9,  82],
       [ 19, 122],
       [ 22,  31],
       [ 22,  61],
       [ 37,  25],
       [ 39,  28],
       [ 46,  81],
       [ 58, 134],
       [ 83,  90],
       [ 91, 147],
       [103,  29],
       [116,  76],
       [123,  99],
       [135,  79],
       [139,  91],
       [145,   3]])

In [291]:
next_moves = next_moves[argsorted]

In [292]:
next_moves

array(['left', 'right', 'right', 'right', 'left', 'left', 'left', 'left',
       'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left',
       'left'], dtype='<U8')

In [305]:
carts[0] == np.array([1, 24])

array([ True,  True])

In [367]:
m = np.array([[1, 2], [1, 1], [0, 1], [0, 0]])

In [327]:
m[m[:, 0].argsort()][]

array([[0, 1],
       [0, 0],
       [1, 2],
       [1, 1]])

In [330]:
m[np.lexsort((m[:, 0], m[:, 1]))]

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 2]])

In [336]:
m[m[:,0].argsort()]

array([[0, 1],
       [0, 0],
       [1, 2],
       [1, 1]])

In [340]:
np.array(sorted(m, key=lambda x: (x[0], x[1])))

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 2]])

In [362]:
m

array([[(1, 1), (2, 2)],
       [(1, 1), (1, 1)],
       [(0, 0), (1, 1)],
       [(0, 0), (0, 0)]], dtype=[('x', '<i8'), ('y', '<i8')])

In [343]:
n = np.array([[0, 0], [0, 1], [1, 1], [1, 2]])

In [345]:
np.argwhere(m == n)

array([[1, 1],
       [2, 1]])

In [358]:
m[np.argsort(m, axis=0, order='x')]

array([[[(0, 0), (1, 1)],
        [(0, 0), (0, 0)]],

       [[(0, 0), (0, 0)],
        [(1, 1), (1, 1)]],

       [[(1, 1), (2, 2)],
        [(0, 0), (1, 1)]],

       [[(1, 1), (1, 1)],
        [(1, 1), (2, 2)]]], dtype=[('x', '<i8'), ('y', '<i8')])

In [350]:
m.dtype

dtype('int64')

In [368]:
np.lexsort((m[:, 0], m[:, 1]))

array([3, 2, 1, 0])

In [371]:
np.random.shuffle(carts)

In [376]:
carts[np.lexsort((carts[:, 1], carts[:, 0]))]

array([[  1,  24],
       [  9,  82],
       [ 19, 122],
       [ 22,  31],
       [ 22,  61],
       [ 37,  25],
       [ 39,  28],
       [ 46,  81],
       [ 58, 134],
       [ 83,  90],
       [ 91, 147],
       [103,  29],
       [116,  76],
       [123,  99],
       [135,  79],
       [139,  91],
       [145,   3]])

In [383]:
carts

array([[145,   3],
       [ 91, 147],
       [ 22,  31],
       [ 39,  28],
       [123,  99],
       [  9,  82],
       [ 22,  61],
       [103,  29],
       [ 37,  25],
       [ 46,  81],
       [ 83,  90],
       [135,  79],
       [ 58, 134],
       [139,  91],
       [116,  76],
       [ 19, 122],
       [  1,  24]])

In [384]:
next_moves

array(['left', 'right', 'right', 'right', 'left', 'left', 'left', 'left',
       'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left',
       'left'], dtype='<U8')

In [388]:
len(next_moves)

17

In [476]:
def find_last_cart():
    tracks = read_input('input_13.txt', '\n')[:-1]
    listed = [[letter for letter in track] for track in tracks]
    np_tracks = np.array(listed)
    carts = np.array(np.where(np.isin(np_tracks, ['<', '>', '^', 'v']))).T
    cart_moves = {'west': np.array([0, -1]),
                  'east': np.array([0, 1]),
                  'north': np.array([-1, 0]),
                  'south': np.array([1, 0])}
    cart_orientations = {'<': 'west',
                         '>': 'east',
                         '^': 'north',
                         'v': 'south'}
    cardinal_dirs = {'north': {'left': 'west', 'straight': 'north', 'right': 'east'},
                     'south': {'left': 'east', 'straight': 'south', 'right': 'west'},
                     'west': {'left': 'south', 'straight': 'west', 'right': 'north'},
                     'east': {'left': 'north', 'straight': 'east', 'right': 'south'}}
    current_orientations = np.array([cart_orientations[np_tracks[row, col]] for row, col in carts])
    next_moves = np.array(['left' for _ in range(len(current_orientations))], dtype='<U8')
    while True:
        lexsorted = np.lexsort((carts[:, 1], carts[:, 0]))
        carts = carts[lexsorted]
        next_moves = next_moves[lexsorted]
        current_orientations = current_orientations[lexsorted]
        diff = False
        for i, cart in enumerate(carts):
            carts[i] += cart_moves[current_orientations[i]]
            spot = np_tracks[carts[i][0], carts[i][1]]
            if len(carts) != len(np.unique(carts, axis=0)):
                diff = True
                uniques, counts = np.unique(carts, axis=0, return_counts=True)
                unique_row = uniques[counts == 2].flatten()
                mask = np.all(carts==unique_row, axis=1)
            if spot == '+':
                change_direction(i, next_moves, current_orientations)
            elif spot == '\\':
                if current_orientations[i] == 'west':
                    new_orientation = 'north'
                elif current_orientations[i] == 'east':
                    new_orientation = 'south'
                elif current_orientations[i] == 'north':
                    new_orientation = 'west'
                elif current_orientations[i] == 'south':
                    new_orientation = 'east'
                current_orientations[i] = new_orientation
            elif spot == '/':
                if current_orientations[i] == 'west':
                    new_orientation = 'south'
                elif current_orientations[i] == 'east':
                    new_orientation = 'north'
                elif current_orientations[i] == 'north':
                    new_orientation = 'east'
                elif current_orientations[i] == 'south':
                    new_orientation = 'west'
                current_orientations[i] = new_orientation
            elif spot in '-|<>^v':
                continue
            else:
                return "You screwed up in spots"
        if diff:
            diff = False
            #import pdb; pdb.set_trace()
            carts = carts[~mask]
            next_moves = next_moves[~mask]
            current_orientations = current_orientations[~mask]
            print(f"remaining carts is {len(carts)}")
            if len(carts) == 1:
                return carts
    return carts

In [477]:
find_last_cart()

remaining carts is 15
remaining carts is 13
remaining carts is 11
remaining carts is 9
remaining carts is 7
remaining carts is 5
remaining carts is 3
remaining carts is 1


array([[125, 116]])

In [397]:
m == m[2, :]

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True, False]])

In [399]:
m[4, :] = np.array([1, 1])

IndexError: index 4 is out of bounds for axis 0 with size 4

In [406]:
m = m.tolist()

In [407]:
m.append([1, 1])

In [408]:
m = np.array(m)

In [409]:
m

array([[1, 2],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 1]])

In [419]:
counts = np.unique(m, return_counts=True, axis=0)

In [420]:
dup = counts[0][counts[1] == 2]

In [421]:
dup

array([[1, 1]])

In [417]:
counts == 2

array([False, False,  True, False])

In [428]:
np.where(counts == dup.flatten())

/home/kurtrm/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


(array([], dtype=int64),)

In [425]:
dup.flatten()

array([1, 1])

In [426]:
counts == dup.flatten()

/home/kurtrm/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [429]:
dup

array([[1, 1]])

In [430]:
counts == dup.flatten()

/home/kurtrm/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [434]:
counts

(array([[0, 0],
        [0, 1],
        [1, 1],
        [1, 2]]), array([1, 1, 2, 1]))

In [435]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([4,5,6])

In [436]:
result = np.all(a==b, axis=1)

In [437]:
result

array([False,  True, False])

In [471]:
m[np.all(m==dup.flatten(), axis=1)]

array([[1, 1],
       [1, 1]])

In [442]:
dup.flatten()

array([1, 1])

In [446]:
np_tracks[0, 0]

' '

In [448]:
np.array([0, 0]) == np.array([0, 0])

array([ True,  True])